default:
  variable_type: ".csv"
  variable:
    variable_names: !expr here::here("worksheets","cchs_sheets", "od_variables.csv")
    variable_details: !expr here::here("worksheets", "cchs_sheets", "cchsflow_variables_details1.csv")
    din_list_oral: !expr here::here("worksheets", "NMS_sheets", "din_list_oral.csv")
    din_list_transdermal: !expr here::here("worksheets", "NMS_sheets", "din_list_transdermal.csv")
    din_list: !expr here::here("worksheets","NMS_sheets", "DIN_list2.csv")
  modules: NULL
  data_type: ".RData"
  data:
    cchs2013_2014: !expr here::here("Data", "cchs2013_2014.RData")
    cchs2015_2016: !expr here::here("Data", "cchs2015_2016.RData")
    cchs2017_2018: !expr here::here("Data", "cchs2017_2018.RData")
#exclusion paramters
dayssupl: 1
quantity: 2
dosage_form: "Inj*"

