default:
  variable_type: ".csv"
  variable:
    variable_names: !expr here::here("worksheets", "od_variables.csv")
    variable_details: !expr here::here("worksheets", "cchsflow_variables_details1.csv")
    DIN_list: !expr here::here("worksheets", "DIN_list.csv")
    DIN_list2: !expr here::here("worksheets", "DIN_list2.csv")
    din_list_oral: !expr here::here("worksheets", "din_list_oral.csv")
  modules: NULL
  data_type: ".RData"
  data:
    cchs2013_2014: !expr here::here("Data", "cchs2013_2014.RData")
    cchs2015_2016: !expr here::here("Data", "cchs2015_2016.RData")
    cchs2017_2018: !expr here::here("Data", "cchs2017_2018.RData")
