---
title: "Summary of Missingness Post-2007"
format: html
---

# Table 1: Missing Variables and Suggested Replacements

This table documents **missing variables in the Canadian Community Health Survey (CCHS)** data post-2007 and provides suggested replacements for data harmonization between PUMF (Public Use Microdata Files) and ICES (Institute for Clinical Evaluative Sciences) linked data.

**Some notes for Orienting Readers**:

-   For all variable names post 2007, the fourth position stands for what type of variable it is:

    -   "G"=grouped: These are almost always specific to the PUMF files. They are grouped (de-identified) versions of the same variables found in the master/shared survey. These are typically unique to PUMF files but some variables have grouped versions in the master/shared files (ex.country of birth) but the number of categories may differ in different versions

    -   "\_"=collected: these are primary questions that are asked directly to participants. These questions are usually the continuous forms of the grouped variables discussed in the previous entry or the precursors used to derive other variables.

    -   "D"= derived variables. These are variables that are derived directly by Stats Can. This naming convention was followed from the years 2007-2014

    -   "DV"= derived variables. Same as "D" designation but specific to cycles post 2015.

+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Variable Name**                                               | **Missing Cycles**                | **Reason for Missingness**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | **Suggested Replacement**                                                                                                                                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADM_RNO- Administrative sequential record                       | All cycles                        | Found only in PUMF. A non-identifying serial number to replace direct identifiers found in master and shared files                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | ICES Knowledge Number for participant tracking                                                                                                                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_005- Help preparing meals                                   | 2015-2016 & 2017-2018             | ADL questionnaire is optional in the identified cycles. In 2015-2016 only NFL, PEI, NS, and NB participants completed questionnaire. Completed only in PEI, NB, and QC in 2017-2018.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Low priority since ADL variables are only potential imputation predictors (for OD project).                                                                                                                                                                                                                                                                                         |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | If variable is required, homecare questionnaire may be of use (HMC_005D and HMC_050D). HMC_050D asks about the need for home care for help making meals, personal care, and housework. However, home care questionnaire not available in 2017 cycle and looks like it may not be linked in 2018 cycle either.                                                                       |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_010- Difficulty running errands                             | 2015-2016 & 2017-2018             | See ADL above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | Same as above                                                                                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_015- Difficult doing everyday housework                     | 2015-2016 & 2017-2018             | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Same as above                                                                                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_020- difficulty personal care                               | 2015-2016 & 2017-2018             | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Same as above. Additionally, there is a personal care questionnaire (PSC_050 to identify severe cases in need of personal care support). However, this is not available in Ontario for 2015-2016 (AB, Nunavut, and PEI)                                                                                                                                                             |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_025- difficulty moving about inside the house               | 2015-2016 & 2017-2018             | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | No direct alternatives. Some general mobility measures may be useful. In 2015, there are mobility questionnaires associated with HUI but those are not linked since they are only in the single 2015 cycle (ex. HUI_090 is a direct equivalent). In 2017-2018, WDM questionnaire has general mobility questions (WDM_015- do you have difficulty walking/climbing steps)            |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ADL_030- difficulty looking after personal finances             | 2015-2016 & 2017-2018             | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | No direct alternatives. Financial decision making might be indirectly assessed through questions about financial situation and behaviour that may be contributing to it (ex. gambling) but no other questions about financial ability post 2015.                                                                                                                                    |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Smoking Variables Pre 2015                                      | 2007-2014                         | Grouped variables, all of which have non grouped alternatives available through ICES                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | remove the G in the variable name and replace with \_ (ex.SMKG01C –\>SMK_01C)                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Smoking variables post 2015                                     | 2015+                             | Incorrectly coded by team                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Most of the conflicts are renaming:                                                                                                                                                                                                                                                                                                                                                 |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMK_05B--\>SMK_050                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMK_05C--\> SMK_055                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMK_09C--\>SMK_90                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMK_204--\>SMK_045                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Also some redundant variables from the pumf, GET RID OF THESE:                                                                                                                                                                                                                                                                                                                      |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMKG09C                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SMKG01C                                                                                                                                                                                                                                                                                                                                                                             |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SLP_01                                                          | 2007-2008, 2011-2012, 2013-2014   | 2007-2008:SLP questionnaire was administered only in NS and YK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | No direct alternatives but there are other measures of poor sleep/drowsiness:                                                                                                                                                                                                                                                                                                       |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2011-2012: Module was optional and only selected in NS,QC, MN, AB, and YK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2007-2008: CCC_035 (sleep apnea) and MED_1P(sleeping pills)                                                                                                                                                                                                                                                                                                                         |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2013-2014: SLP questionnaire was optional, administered only in MN, PEI, AB, and NWT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | 2011-2012: CCC_035 (sleep apnea), DIS_10A(Fatigue), DRV_04(Drowsiness while driving)                                                                                                                                                                                                                                                                                                |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 2013-2014:                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | `CCC_035`, `DRV_04`                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Some other variables:                                                                                                                                                                                                                                                                                                                                                               |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | MEX_090 (co_sleeping with a baby/child, only for mothers)                                                                                                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SLP_02                                                          | 2013-2014                         | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | No alternatives                                                                                                                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SLP_04                                                          | 2013-2014                         | See above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | No alternatives                                                                                                                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| WTS_M                                                           | All cycles                        | Wrong variable, only available in master file                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | WTS_S/ WTS_SHH--\> Weights adjusted to those who refused data sharing to provincial data holders (like ICES)                                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| All socio-demographic (SDC-) and height/weight variables (HWT-) | 2007+                             | Grouped variables that can be derived from ICES alternatives. Also some spelling mistakes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | ICES alternatives: remove G to get full variables. The grouped variables can be recreated in the master file by collapsing categories/ categorizing continuous variables                                                                                                                                                                                                            |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Pre 2015: replace G with D                                                                                                                                                                                                                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Post 2015: replace G with DV                                                                                                                                                                                                                                                                                                                                                        |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | EX: HWTGHTM (PUMF 2014)--\>HWTDHTM (ICES 2014)--\> HWTDVHTM (ICES 2015+)                                                                                                                                                                                                                                                                                                            |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | ex: SDCGCGT(PUMF2014)--\> SDCDCGT(ICES PRE 2015)--\> SDCDVCGT                                                                                                                                                                                                                                                                                                                       |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **Notable exception:** country of birth is consistently grouped into 10 or 7 NOT 12/13 CATEGORIES in the ICES files.                                                                                                                                                                                                                                                                |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SDCGCB13( 13 category PUMF 2014)--\> SDCGCB12( 12 category pre-2013 PUMF) -–\> SDCGCB(7 category PRE-2013)--\> SDCGCB10(10 category ICES 2011-2014)--\> SDCDVCB (POST 2015)                                                                                                                                                                                                         |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | If you want to recreate the groupings in the PUMF, you can do so by categorizing the raw country of birth variable:                                                                                                                                                                                                                                                                 |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | SDCCCB(2007-2010)--\>SDCCCB10(2011-2012)--\>SDCCCB13(2013-2014                                                                                                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HUI Variables VISION AND HEARING                                | 2007-2008, 2011-2012, 2015+       | HUI questionnaire was optional and only completed in NS in 07-08, and only completed in MN in 11-12. HUI questionnaire is available for all provinces for the single 2015 cycle. However, single cycles are not linked and can not be used. In 2015-2016 double cycle, only the territories participated. In 2018, HUI was scraped entirely in favour of WDM questionnaire, a consolidated measure of the same physical and cognitive abilities (for the purpose of lowering response burden). These new WDM questions correspond directly to derived HUI variables from previous cycles, with slightly less granular groupings. All provinces participated in this redesigned questionnaire in 2017-2018. | Oh boy, this one is a long one                                                                                                                                                                                                                                                                                                                                                      |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | CCHS 2007-08:                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | -No alternatives, all HUI conditions are grouped into a singular question (RAC_1): Do you have any difficulty hearing, seeing, communicating, walking, climbing stairs, bending, learning or doing any similar activities?                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 2011-2012:                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | --No alternatives for hearing. For vision, there questions about eye exams and optometrist and hearing specialist consults (CHP_06 and CHP\_). These could be used for imputation but not as proxies                                                                                                                                                                                |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Post 2015:                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | In the description below, the HUI variable for pre 2015 is provided (post 2015 name in bracket).                                                                                                                                                                                                                                                                                    |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Raw variables are summed to produce derived variables. These derived variables are the only ones that have WDM equivalents:                                                                                                                                                                                                                                                         |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **Variables with direct WDM equivalents:**                                                                                                                                                                                                                                                                                                                                          |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **Vision:**                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Raw variables: HUI_01(HUI_005)+ HUI_02(HUI_010)+ HUI_03(HUI_015)+ HUI_04(HUI_020)+ HUI_05(HUI_025)= HUIDVIS(HUIDVVIS)= WDM_005                                                                                                                                                                                                                                                      |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **Hearing:**                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Exact same logic as vision: sum(HUI_06(HUI_030) to HUI_010(HUI_050)= HUIDHER(HUIDVHER)= WDM_010                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **important:** DIfferences in grouping between WDM and HUI DERIVED Variables. WDM variables have 4 groups compared to six for derived HUI variables. WDM does not differentiate between those with and without aids (glasses, hearing aids etc..) while HUI does. Harmonization would dictate collapsing 4 of the categories in derived HUI variable into 2 categories, simple fix. |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | For more information about harmonization visit link in the email                                                                                                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fruit and vegetable intake questionnaire                        | 2017-2018                         | This questionnaire was actually considered theme content for the single 2017 cycle, however, single cycles are not linked. In 2018, only participants from the territories were asked the question so it will not be present in ICES data                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | No alternatives identified. There are some questions about food decisions and food guide use but no questions about diet specifically. If the team is interested, I can look further into these potential variables but they don't look like they can be proxies.                                                                                                                   |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| INCDVRCA                                                        | 2015-2016 and 2017-2018           | Incorrect coding for 2015-2016, not present in 2017-2018.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | For 2015-2016: INCDVSCA is the correct variable name for ICES data (i don't know why this is the case)                                                                                                                                                                                                                                                                              |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | For 2017-2018: Income is no longer self reported, it is derived from participant tax records (CRA). ICES did not complete the special process necessary for                                                                                                                                                                                                                         |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Dental visit (DEN-)                                             | 2007-2008, 11-12, 15-16           | Modules was optional for most years.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DEN_132 (DEN_035): when was the last time you went to a dentist/ dental professional                                                                                                                                                                                                                                                                                                |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2007-2008: NFL, AB, NWT. 08 alone is present in ON but not linked                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | For 2007-2008 and 2015+                                                                                                                                                                                                                                                                                                                                                             |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2011-2012: NFL, MN, AB, NWT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | There is a possible alternative over a shorter period:                                                                                                                                                                                                                                                                                                                              |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2015-2016:NFL, AB, BC, NU                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **CHP_14(CHP_080 POST 2015):** Have you seen or talked to a dentist/dental professional in the past 12 months. This variable lso called HCU_2EE in 07-08                                                                                                                                                                                                                            |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | Note: I have little to no familiairity with the dental variables. Please take suggestions with a grain of salt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Possible harmonzation: technically (though there are no existing studies that do this) you can collapse the DEN variable to mimic the CHP variable and the harmonized variable would be dental care over the past year (yes/no)                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | For 2011-2012:                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | CHP and DEN questionnaires not selected by Ontario in 2011, I couldn't find alternatives. Suprisingly, the ICES website indicates that, for the CHP questionnaire (which is not asked in Ontario in 2011) ICES actually linked the 2012 cohort on its own. **ASK SHAN about this.**                                                                                                 |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Oral health variables (OH-)                                     | 2007-2008, 2011-2012, & 2015-2016 | Who comes up with these changes? Is the goal to make it as confusing as possible?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | These are highly specific questions, how frequently do you brush your teeth, do you wear dentures etc... I couldn't find any direct alternatives.                                                                                                                                                                                                                                   |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | Prior to 2015, the oral health questionnaire was split into 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | OH1- Oral habits related to consumption of food (what types of food are you able to consume without discomfort)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | OH2- Oral health access, and Oral health treatment (brushing teeth, access to dentist, having dentures etc..)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | For OH1:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2011-2012: OH1 is only missing in this cycle, it was optional and was selected only by MB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | For OH2:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2007-2008: Optional and selected only in NFL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2011-2012: Optional and only selected by MB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | After 2015:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | Oral health questionnaire is consolidated in a single set of items (OHT-)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   | 2015-2016: optional and selected only in NU                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DHHGAGE                                                         | 2007+                             | Incorrect variable. This variable is the grouped age specific only to PUMF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Replace with: DHH_AGE                                                                                                                                                                                                                                                                                                                                                               |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | or                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                 |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | ICES age if your index date is not survey admin date                                                                                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+